enable-magisk-update = true
parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide ads' 'Video ads' 'Remove viewer discretion dialog' 'Seekbar' 'Hide info cards' 'SponsorBlock' 'Remove background playback restrictions' 'Video quality'"
exclusive-patches = true
